language: node_js
node_js:
  - "7"
cache:
  npm: true
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install --save react
  - npm install --save react-dom
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run test:coverage
after_success:
  - npm run coveralls
